import type { ProductResponse, SuccessResponse } from '@noaignite/centra-types'

export const productResponse: SuccessResponse<ProductResponse> = {
  token: 'e37b0c13e1gv4bdkceigir9go5',
  product: {
    available: true,
    modifiedAt: '2024-02-16 10:29:55',
    createdAt: '2024-02-16 10:15:22',
    relatedProducts: [
      {
        available: true,
        relatedProducts: [
          {
            product: '1',
            available: true,
            media: {
              standard: [
                'https://example.centracdn.net/client/dynamic/images/1_9adfeff6f2-red.jpg',
                'https://example.centracdn.net/client/dynamic/images/1_3a541eaec0-no-connect.jpg',
              ],
            },
            relation: 'variant',
          },
        ],
        bundleInfo: {
          bundle: 42,
          priceType: 'static',
          type: 'fixed',
          priceOfItems: '130 SEK',
          priceMin: '130 SEK',
          priceMinAsNumber: 130,
          priceMax: '150 SEK',
          priceMaxAsNumber: 150,
          discount: 7,
        },
        product: '60',
        name: 'Test Product',
        uri: 'test-product',
        sku: '123Yo',
        productSku: '123',
        brand: '1',
        brandName: 'Brand',
        brandUri: 'brand',
        collection: '1',
        collectionName: 'Collection',
        collectionUri: 'collection',
        modifiedAt: '2024-02-16 10:29:55',
        createdAt: '2024-02-16 10:15:22',
        variantName: 'Nice',
        countryOrigin: '',
        excerpt: 'AAA',
        excerptHtml: '<p>AAA</p>',
        description: 'BBB',
        descriptionHtml: '<p>BBB</p>',
        metaTitle: 'CCC',
        metaDescription: 'EEE',
        metaKeywords: 'DDD',
        stockUnit: '',
        category: '1',
        centraProduct: '1',
        centraVariant: '2465',
        itemQuantityMinimum: 1,
        itemQuantityMultipleOf: 1,
        price: '10.00 USD',
        priceAsNumber: 10,
        priceBeforeDiscount: '10.00 USD',
        priceBeforeDiscountAsNumber: 10,
        discountPercent: 0,
        lowestPrice: [
          {
            periodDays: 30,
            price: '8.00 SEK',
            priceAsNumber: 8,
            priceBeforeDiscount: '10.00 SEK',
            priceBeforeDiscountAsNumber: 10,
          },
        ],
        showAsOnSale: false,
        showAsNew: false,
        itemTable: {
          unit: '',
          x: ['S', 'M', 'L', 'XL'],
          dividerSymbol: 'x',
          y: [],
        },
        tableMappings: {
          'Us sizes': {
            unit: 'Us sizes',
            x: {
              S: 'us 5',
              M: 'us 6',
              L: 'us 7',
              XL: 'us 8',
            },
            y: [],
            dividerSymbol: ['x'],
            countries: ['AX', 'AL'],
          },
        },
        defaultLocalizedChart: 'Us sizes',
        items: [
          {
            item: '60-29',
            ean: '',
            upc: '',
            sizeId: '1',
            itemTableY: 0,
            itemTableX: 0,
            name: 'S',
            sku: '123Yo',
            stock: 'yes',
          },
        ],
        categoryName: ['Shop', 'Men', 'Linnen'],
        categoryUri: 'shop/men/linnen',
        categories: [
          {
            sortOrder: 1000010,
            name: ['Shop', 'Men', 'Linnen'],
            category: '1',
            uri: 'shop/men/linnen',
          },
        ],
        media: {
          standard: [
            'https://example.centracdn.net/client/dynamic/images/1_3a541eaec0-no-connect.jpg',
          ],
        },
        preview: false,
        subscriptionPlans: [
          {
            name: 'Save 5% with monthly subscription',
            intervalValue: 1,
            intervalType: 'month',
            discountPercent: 5,
            shippingType: 'DYNAMIC',
            subscriptionPlan: 17,
            status: 'ACTIVE',
            price: '100 USD',
            priceAsNumber: 100,
            priceAfterDiscount: '95 USD',
            priceAfterDiscountAsNumber: 95,
          },
        ],
        relation: 'variant',
      },
    ],
    bundleInfo: {
      bundle: 42,
      priceType: 'static',
      type: 'fixed',
      priceOfItems: '130 SEK',
      priceMin: '130 SEK',
      priceMinAsNumber: 130,
      priceMax: '150 SEK',
      priceMaxAsNumber: 150,
      discount: 7,
    },
    product: '60',
    name: 'Test Product',
    uri: 'test-product',
    sku: '123Yo',
    productSku: '123',
    brand: '1',
    brandName: 'Brand',
    brandUri: 'brand',
    collection: '1',
    collectionName: 'Collection',
    collectionUri: 'collection',
    variantName: 'Nice',
    countryOrigin: '',
    excerpt: 'AAA',
    excerptHtml: '<p>AAA</p>',
    description: 'BBB',
    descriptionHtml: '<p>BBB</p>',
    metaTitle: 'CCC',
    metaDescription: 'EEE',
    metaKeywords: 'DDD',
    stockUnit: '',
    category: '1',
    centraProduct: '1',
    centraVariant: '2465',
    itemQuantityMinimum: 1,
    itemQuantityMultipleOf: 1,
    price: '10.00 USD',
    priceAsNumber: 10,
    priceBeforeDiscount: '10.00 USD',
    priceBeforeDiscountAsNumber: 10,
    discountPercent: 0,
    lowestPrice: [
      {
        periodDays: 30,
        price: '8.00 SEK',
        priceAsNumber: 8,
        priceBeforeDiscount: '10.00 SEK',
        priceBeforeDiscountAsNumber: 10,
      },
    ],
    showAsOnSale: false,
    showAsNew: false,
    itemTable: {
      unit: '',
      x: ['S', 'M', 'L', 'XL'],
      dividerSymbol: 'x',
      y: [],
    },
    tableMappings: {
      'Us sizes': {
        unit: 'Us sizes',
        x: {
          S: 'us 5',
          M: 'us 6',
          L: 'us 7',
          XL: 'us 8',
        },
        y: [],
        dividerSymbol: ['x'],
        countries: ['AX', 'AL'],
      },
    },
    defaultLocalizedChart: 'Us sizes',
    items: [
      {
        item: '60-29',
        ean: '',
        upc: '',
        sizeId: '1',
        itemTableY: 0,
        itemTableX: 0,
        name: 'S',
        sku: '123Yo',
        stock: 'yes',
      },
    ],
    categoryName: ['Shop', 'Men', 'Linnen'],
    categoryUri: 'shop/men/linnen',
    categories: [
      {
        sortOrder: 1000010,
        name: ['Shop', 'Men', 'Linnen'],
        category: '1',
        uri: 'shop/men/linnen',
      },
    ],
    media: {
      standard: ['https://example.centracdn.net/client/dynamic/images/1_3a541eaec0-no-connect.jpg'],
    },
    preview: false,
    subscriptionPlans: [
      {
        name: 'Save 5% with monthly subscription',
        intervalValue: 1,
        intervalType: 'month',
        discountPercent: 5,
        shippingType: 'DYNAMIC',
        subscriptionPlan: 17,
        status: 'ACTIVE',
        price: '100 USD',
        priceAsNumber: 100,
        priceAfterDiscount: '95 USD',
        priceAfterDiscountAsNumber: 95,
      },
    ],
    relation: 'variant',
  },
}
