import type { SelectionResponse, SuccessResponse } from '@noaignite/centra-types'

export const selectionEmptyResponse: SuccessResponse<SelectionResponse> = {
  token: 'e37b0c13e1gv4bdkceigir9go5',
  selection: {
    language: 'en',
    currency: 'USD',
    paymentMethod: 'dummy',
    paymentMethodName: 'dummy payment',
    shippingMethod: 'usd',
    shippingMethodName: 'Standard',
    items: [],
    discounts: {
      anyDiscount: false,
      discount: '0.00 USD',
      discountAsNumber: 0,
      automaticDiscounts: [],
      vouchers: [],
    },
    totals: {
      itemsTotalPrice: '20.00 USD',
      itemsTotalPriceAsNumber: 20,
      totalDiscountPrice: false,
      totalDiscountPriceAsNumber: false,
      shippingPrice: '0.00 USD',
      shippingPriceAsNumber: 0,
      handlingCostPrice: '0.00 USD',
      handlingCostPriceAsNumber: 0,
      totalQuantity: 2,
      taxDeducted: false,
      taxDeductedAsNumber: false,
      taxAdded: false,
      taxAddedAsNumber: false,
      taxPercent: 0,
      grandTotalPrice: '20.00 USD',
      grandTotalPriceAsNumber: 20,
      grandTotalPriceTax: '0.00 USD',
      grandTotalPriceTaxAsNumber: 0,
    },
    vatExempt: false,
    address: {
      firstName: '',
      lastName: '',
      email: '',
      phoneNumber: '',
      company: '',
      address1: '',
      address2: '',
      zipCode: '',
      city: '',
      state: '',
      country: '',
      vatNumber: '',
    },
    shippingAddress: {
      firstName: '',
      lastName: '',
      email: '',
      phoneNumber: '',
      company: '',
      address1: '',
      address2: '',
      zipCode: '',
      city: '',
      state: '',
      country: '',
    },
    additionalNotes: '',
    currencyFormat: {
      currency: 'USD',
      name: 'USD',
      prefix: '',
      suffix: ' USD',
      decimalPoint: '.',
      decimalDigits: '2',
      uri: 'usd',
    },
  },
  languages: [
    {
      language: 'en',
      name: 'English',
      default: true,
    },
    {
      language: 'sv',
      name: 'Swedish',
      default: false,
    },
  ],
  paymentMethods: [
    {
      paymentMethod: 'adyen-checkout',
      name: 'Adyen Checkout',
      handlingCost: '0.00 USD',
      handlingCostAsNumber: 0,
    },
    {
      paymentMethod: 'klarna-invoice',
      name: 'Klarna Invoice',
      handlingCost: '2.00 USD',
      handlingCostAsNumber: 25,
    },
    {
      paymentMethod: 'klarna-checkout',
      name: 'Klarna Checkout',
      handlingCost: '0.00 USD',
      handlingCostAsNumber: 0,
    },
  ],
  paymentFields: {
    termsAndConditions: {
      type: 'boolean',
      visible: true,
      required: true,
    },
    address: {
      email: {
        type: 'string',
        visible: true,
        required: true,
      },
      company: {
        type: 'string',
        visible: true,
        required: true,
      },
      firstName: {
        type: 'string',
        visible: true,
        required: true,
      },
      lastName: {
        type: 'string',
        visible: true,
        required: true,
      },
      address1: {
        type: 'string',
        visible: true,
        required: true,
      },
      address2: {
        type: 'string',
        visible: true,
        required: false,
      },
      zipCode: {
        type: 'string',
        visible: true,
        required: true,
      },
      city: {
        type: 'string',
        visible: true,
        required: true,
      },
      state: {
        type: 'string',
        visible: true,
        required: true,
      },
      country: {
        type: 'string',
        visible: true,
        required: true,
      },
      phoneNumber: {
        type: 'string',
        visible: true,
        required: true,
      },
      identityNumber: {
        type: 'string',
        visible: true,
        required: true,
      },
      vatNumber: {
        type: 'string',
        visible: true,
        required: true,
      },
      houseNumber: {
        type: 'string',
        visible: false,
        required: false,
      },
      houseExtension: {
        type: 'string',
        visible: false,
        required: false,
      },
      newsletter: {
        type: 'boolean',
        visible: true,
        required: false,
      },
    },
    shippingAddress: {
      email: {
        type: 'string',
        visible: true,
        required: true,
      },
      company: {
        type: 'string',
        visible: true,
        required: true,
      },
      firstName: {
        type: 'string',
        visible: true,
        required: true,
      },
      lastName: {
        type: 'string',
        visible: true,
        required: true,
      },
      address1: {
        type: 'string',
        visible: true,
        required: true,
      },
      address2: {
        type: 'string',
        visible: true,
        required: false,
      },
      zipCode: {
        type: 'string',
        visible: true,
        required: true,
      },
      city: {
        type: 'string',
        visible: true,
        required: true,
      },
      state: {
        type: 'string',
        visible: true,
        required: true,
      },
      country: {
        type: 'string',
        visible: true,
        required: true,
      },
      phoneNumber: {
        type: 'string',
        visible: true,
        required: true,
      },
      houseNumber: {
        type: 'string',
        visible: false,
        required: false,
      },
      houseExtension: {
        type: 'string',
        visible: false,
        required: false,
      },
    },
  },
  shippingMethods: [
    {
      shippingMethod: 'dhl-express',
      name: 'DHL Express',
      price: '5.00 USD',
      priceAsNumber: 5,
    },
    {
      shippingMethod: 'standard',
      name: 'Standard',
      price: '0.00 USD',
      priceAsNumber: 0,
    },
    {
      shippingMethod: 'fedex-ground',
      name: 'Fedex Ground',
      price: '20.00 USD',
      priceAsNumber: 20,
    },
  ],
  countries: [
    {
      country: 'AU',
      name: 'Australia',
      eu: false,
      language: 'en',
      states: [
        {
          state: 'ACT',
          name: 'Australian Capital Territory',
        },
        {
          state: 'NSW',
          name: 'New South Wales',
        },
      ],
    },
    {
      country: 'JP',
      name: 'Japan',
      eu: false,
      language: 'en',
      currency: 'JPY',
    },
  ],
  loggedIn: {
    customer: '123',
    email: 'hello@world.com',
    firstName: 'First',
    lastName: 'Last',
    gender: '',
    address1: 'Stret',
    address2: '',
    zipCode: '123',
    city: 'City',
    state: '',
    country: 'SE',
    phoneNumber: '123456789',
    language: 'sv',
    newsletter: false,
  },
  location: {
    country: 'SE',
    name: 'Sweden',
    state: null,
    stateName: '',
    eu: true,
    shipTo: true,
    language: {
      language: 'en',
      name: 'English',
      default: true,
    },
  },
}
