import type { SelectionResponse, SuccessResponse } from '@noaignite/centra-types'

export const selectionResponse: SuccessResponse<SelectionResponse> = {
  token: 'e37b0c13e1gv4bdkceigir9go5',
  selection: {
    language: 'en',
    currency: 'USD',
    paymentMethod: 'dummy',
    paymentMethodName: 'dummy payment',
    shippingMethod: 'usd',
    shippingMethodName: 'Standard',
    items: [
      {
        item: '60-29',
        productUrl: null,
        category: null,
        comment: '',
        size: 'S',
        sku: '123Yo',
        ean: '1234567899',
        upc: '123456',
        quantity: 1,
        subscriptionPlan: {
          name: 'Save 5% with monthly subscription',
          intervalValue: 1,
          intervalType: 'month',
          discountPercent: 5,
          shippingType: 'DYNAMIC',
          subscriptionPlan: 17,
          status: 'ACTIVE',
          price: '100 USD',
          priceAsNumber: 100,
          priceAfterDiscount: '95 USD',
          priceAfterDiscountAsNumber: 95,
        },
        line: '0416151f70083fe08677a929394a0351',
        priceEach: '10.00 USD',
        priceEachAsNumber: 10,
        totalPrice: '10.00 USD',
        totalPriceAsNumber: 10,
        priceEachBeforeDiscount: '10.00 USD',
        priceEachBeforeDiscountAsNumber: 10,
        anyDiscount: false,
        campaign: {
          name: 'campaign 50%',
          discount: '50.00 SEK',
          discountAsNumber: 50,
        },
        taxPercent: 0,
        priceEachWithoutTax: '10.00 USD',
        priceEachWithoutTaxAsNumber: 10,
        priceEachReduction: '0.00 USD',
        priceEachReductionAsNumber: 0,
        totalPriceBeforeDiscount: '10.00 USD',
        totalPriceBeforeDiscountAsNumber: 10,
        product: {
          product: '60',
          name: 'Test Product',
          uri: 'test-product',
          sku: '123Yo',
          productSku: '123',
          brand: '1',
          brandName: 'Brand',
          brandUri: 'brand',
          collection: '1',
          collectionName: 'Collection',
          collectionUri: 'collection',
          modifiedAt: '2024-02-16 10:29:55',
          createdAt: '2024-02-16 10:15:22',
          variantName: 'Nice',
          countryOrigin: '',
          excerpt: 'AAA',
          excerptHtml: '<p>AAA</p>',
          description: 'BBB',
          descriptionHtml: '<p>BBB</p>',
          metaTitle: 'CCC',
          metaDescription: 'EEE',
          metaKeywords: 'DDD',
          stockUnit: '',
          category: '1',
          centraProduct: '1',
          centraVariant: '2465',
          itemQuantityMinimum: 1,
          itemQuantityMultipleOf: 1,
          price: '10.00 USD',
          priceAsNumber: 10,
          priceBeforeDiscount: '10.00 USD',
          priceBeforeDiscountAsNumber: 10,
          discountPercent: 0,
          lowestPrice: [
            {
              periodDays: 30,
              price: '8.00 SEK',
              priceAsNumber: 8,
              priceBeforeDiscount: '10.00 SEK',
              priceBeforeDiscountAsNumber: 10,
            },
          ],
          showAsOnSale: false,
          showAsNew: false,
          itemTable: {
            unit: '',
            x: ['S', 'M', 'L', 'XL'],
            dividerSymbol: 'x',
            y: [],
          },
          tableMappings: {
            'Us sizes': {
              unit: 'Us sizes',
              x: {
                S: 'us 5',
                M: 'us 6',
                L: 'us 7',
                XL: 'us 8',
              },
              y: [],
              dividerSymbol: ['x'],
              countries: ['AX', 'AL'],
            },
          },
          defaultLocalizedChart: 'Us sizes',
          items: [
            {
              item: '60-29',
              ean: '',
              upc: '',
              sizeId: '1',
              itemTableY: 0,
              itemTableX: 0,
              name: 'S',
              sku: '123Yo',
            },
          ],
          categoryName: ['Shop', 'Men', 'Linnen'],
          categoryUri: 'shop/men/linnen',
          categories: [
            {
              sortOrder: 1000010,
              name: ['Shop', 'Men', 'Linnen'],
              category: '1',
              uri: 'shop/men/linnen',
            },
          ],
          media: {
            standard: [
              'https://example.centracdn.net/client/dynamic/images/1_3a541eaec0-no-connect.jpg',
            ],
          },
          preview: false,
          subscriptionPlans: [
            {
              name: 'Save 5% with monthly subscription',
              intervalValue: 1,
              intervalType: 'month',
              discountPercent: 5,
              shippingType: 'DYNAMIC',
              subscriptionPlan: 17,
              status: 'ACTIVE',
              price: '100 USD',
              priceAsNumber: 100,
              priceAfterDiscount: '95 USD',
              priceAfterDiscountAsNumber: 95,
            },
          ],
          relation: 'variant',
        },
      },
    ],
    discounts: {
      anyDiscount: false,
      discount: '0.00 USD',
      discountAsNumber: 0,
      automaticDiscounts: [],
      vouchers: [],
    },
    totals: {
      itemsTotalPrice: '20.00 USD',
      itemsTotalPriceAsNumber: 20,
      totalDiscountPrice: false,
      totalDiscountPriceAsNumber: false,
      shippingPrice: '0.00 USD',
      shippingPriceAsNumber: 0,
      handlingCostPrice: '0.00 USD',
      handlingCostPriceAsNumber: 0,
      totalQuantity: 2,
      taxDeducted: false,
      taxDeductedAsNumber: false,
      taxAdded: false,
      taxAddedAsNumber: false,
      taxPercent: 0,
      grandTotalPrice: '20.00 USD',
      grandTotalPriceAsNumber: 20,
      grandTotalPriceTax: '0.00 USD',
      grandTotalPriceTaxAsNumber: 0,
    },
    vatExempt: false,
    address: {
      firstName: '',
      lastName: '',
      email: '',
      phoneNumber: '',
      company: '',
      address1: '',
      address2: '',
      zipCode: '',
      city: '',
      state: '',
      country: '',
      vatNumber: '',
    },
    shippingAddress: {
      firstName: '',
      lastName: '',
      email: '',
      phoneNumber: '',
      company: '',
      address1: '',
      address2: '',
      zipCode: '',
      city: '',
      state: '',
      country: '',
    },
    additionalNotes: '',
    currencyFormat: {
      currency: 'USD',
      name: 'USD',
      prefix: '',
      suffix: ' USD',
      decimalPoint: '.',
      decimalDigits: '2',
      uri: 'usd',
    },
  },
  languages: [
    {
      language: 'en',
      name: 'English',
      default: true,
    },
    {
      language: 'sv',
      name: 'Swedish',
      default: false,
    },
  ],
  paymentMethods: [
    {
      paymentMethod: 'adyen-checkout',
      name: 'Adyen Checkout',
      handlingCost: '0.00 USD',
      handlingCostAsNumber: 0,
    },
    {
      paymentMethod: 'klarna-invoice',
      name: 'Klarna Invoice',
      handlingCost: '2.00 USD',
      handlingCostAsNumber: 25,
    },
    {
      paymentMethod: 'klarna-checkout',
      name: 'Klarna Checkout',
      handlingCost: '0.00 USD',
      handlingCostAsNumber: 0,
    },
  ],
  paymentFields: {
    termsAndConditions: {
      type: 'boolean',
      visible: true,
      required: true,
    },
    address: {
      email: {
        type: 'string',
        visible: true,
        required: true,
      },
      company: {
        type: 'string',
        visible: true,
        required: true,
      },
      firstName: {
        type: 'string',
        visible: true,
        required: true,
      },
      lastName: {
        type: 'string',
        visible: true,
        required: true,
      },
      address1: {
        type: 'string',
        visible: true,
        required: true,
      },
      address2: {
        type: 'string',
        visible: true,
        required: false,
      },
      zipCode: {
        type: 'string',
        visible: true,
        required: true,
      },
      city: {
        type: 'string',
        visible: true,
        required: true,
      },
      state: {
        type: 'string',
        visible: true,
        required: true,
      },
      country: {
        type: 'string',
        visible: true,
        required: true,
      },
      phoneNumber: {
        type: 'string',
        visible: true,
        required: true,
      },
      identityNumber: {
        type: 'string',
        visible: true,
        required: true,
      },
      vatNumber: {
        type: 'string',
        visible: true,
        required: true,
      },
      houseNumber: {
        type: 'string',
        visible: false,
        required: false,
      },
      houseExtension: {
        type: 'string',
        visible: false,
        required: false,
      },
      newsletter: {
        type: 'boolean',
        visible: true,
        required: false,
      },
    },
    shippingAddress: {
      email: {
        type: 'string',
        visible: true,
        required: true,
      },
      company: {
        type: 'string',
        visible: true,
        required: true,
      },
      firstName: {
        type: 'string',
        visible: true,
        required: true,
      },
      lastName: {
        type: 'string',
        visible: true,
        required: true,
      },
      address1: {
        type: 'string',
        visible: true,
        required: true,
      },
      address2: {
        type: 'string',
        visible: true,
        required: false,
      },
      zipCode: {
        type: 'string',
        visible: true,
        required: true,
      },
      city: {
        type: 'string',
        visible: true,
        required: true,
      },
      state: {
        type: 'string',
        visible: true,
        required: true,
      },
      country: {
        type: 'string',
        visible: true,
        required: true,
      },
      phoneNumber: {
        type: 'string',
        visible: true,
        required: true,
      },
      houseNumber: {
        type: 'string',
        visible: false,
        required: false,
      },
      houseExtension: {
        type: 'string',
        visible: false,
        required: false,
      },
    },
  },
  shippingMethods: [
    {
      shippingMethod: 'dhl-express',
      name: 'DHL Express',
      price: '5.00 USD',
      priceAsNumber: 5,
    },
    {
      shippingMethod: 'standard',
      name: 'Standard',
      price: '0.00 USD',
      priceAsNumber: 0,
    },
    {
      shippingMethod: 'fedex-ground',
      name: 'Fedex Ground',
      price: '20.00 USD',
      priceAsNumber: 20,
    },
  ],
  countries: [
    {
      country: 'AU',
      name: 'Australia',
      eu: false,
      language: 'en',
      states: [
        {
          state: 'ACT',
          name: 'Australian Capital Territory',
        },
        {
          state: 'NSW',
          name: 'New South Wales',
        },
      ],
    },
    {
      country: 'JP',
      name: 'Japan',
      eu: false,
      language: 'en',
      currency: 'JPY',
    },
  ],
  loggedIn: {
    customer: '123',
    email: 'hello@world.com',
    firstName: 'First',
    lastName: 'Last',
    gender: '',
    address1: 'Stret',
    address2: '',
    zipCode: '123',
    city: 'City',
    state: '',
    country: 'SE',
    phoneNumber: '123456789',
    language: 'sv',
    newsletter: false,
  },
  location: {
    country: 'SE',
    name: 'Sweden',
    state: null,
    stateName: '',
    eu: true,
    shipTo: true,
    language: {
      language: 'en',
      name: 'English',
      default: true,
    },
  },
}
