name: CI:Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

env:
  HUSKY: 0

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.sha}}
          fetch-depth: 0

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check changeset status
        if: github.actor != 'dependabot[bot]'
        run: pnpm ci:status

      - name: Run build
        run: pnpm build

      - name: Run tests with coverage
        run: pnpm ci:test

      - name: Upload coverage to Codecov
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./**/lcov.info
          fail_ci_if_error: true
