name: CI:Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

env:
  HUSKY: 0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.sha}}
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check changeset status
        if: github.actor != 'dependabot[bot]'
        run: pnpm run ci:status

      - name: Run tests
        run: pnpm run ci:test
